sudo: true
dist: xenial
services:
  - docker

jobs:
  include:
    - stage: Test
      name: "Unit and Http tests"
      install:
        # Building Docker images
        - docker-compose -f ./docker-compose-test.yml build -m 8g
      script:
        - docker run -v $(pwd):/appsrc -w /appsrc "gradle -Dtest.http=true testReport"

