sudo: true
dist: xenial
services:
  - docker

jobs:
  include:
    - stage: Unit Test
      name: "Unit tests"
      install:
        # Building Docker images
        - docker-compose -f ./docker-compose-test.yml build -m 8g
      script:
        - docker run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -v $(pwd):/appsrc -w /appsrc/app carnival_app gradle test coveralls --console=plain --continue -Dtest.http=false