version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /appsrc/app
    command: bash
    tty: true
    stdin_open: true
    volumes:
      - "./:/appsrc"